// Generated by MyTester
// Run ID: run_32142f54-2539-46b0-9144-7a688f86b9d8
// Test case ID: db969528-dd0e-4628-96d9-db7eb4914339
// Generated at: 2026-07-13T03:06:28.768Z
import { test, expect } from '@playwright/test';
test('Vérifier le champ "Message *"', async ({ page }) => {
    await page.goto('https://workspace.lifeintelligente.com/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetField = page
        .getByLabel(/Message/i)
        .or(page.getByPlaceholder(/Message/i))
        .or(page.locator('input[name*="message" i], textarea[name*="message" i], input[id*="message" i], textarea[id*="message" i]'))
        .first();
    await expect(targetField).toBeVisible();
    await expect(targetField).toBeEnabled();
    await targetField.fill('Message de test automatisé');
    await expect(targetField).toHaveValue('Message de test automatisé');
    // Résultat attendu : Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
});