// Generated by MyTester
// Run ID: run_1787eb28-27ce-47b1-b8c8-8ae1f06906a5
// Test case ID: f808e4d3-a6fe-4e9b-abc6-de6fc6750973
// Generated at: 2026-07-18T16:13:36.839Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('link', { name: 'Home link' }).click();
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('link', { name: 'Home link' }).click();
    await page.getByRole('button', { name: 'Sign in to your account' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('button', { name: 'Google' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('textbox', { name: 'Email or phone' }).click();
    await page1.getByRole('textbox', { name: 'Email or phone' }).fill('hhh');
    await page1.getByRole('button', { name: 'Next' }).click();
});