// Generated by MyTester
// Run ID: run_a0fdc78a-8043-4364-aad9-d03e1738ec53
// Test case ID: 8a78b03c-331d-4c50-a5f2-c46a288d3749
// Generated at: 2026-07-18T15:54:09.109Z
import { test, expect } from '@playwright/test';
test('Vérifier le chargement de la page "Just a moment..."', async ({ page }) => {
    await page.goto('https://www.fbi.gov/investigate', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    await expect(page).toHaveTitle(/.+/);
    // Résultat attendu : La page doit afficher son contenu principal et rester accessible.
});