// Generated by MyTester
// Run ID: run_e56f5155-66f9-477c-a581-f0fde7ef6135
// Test case ID: cc3c47bb-02ca-44a2-ba15-7dd14f045713
// Generated at: 2026-08-08T21:53:47.509Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.youte.com/');
    await page.getByRole('combobox', { name: 'Search' }).click();
    await page.getByRole('combobox', { name: 'Search' }).fill('football');
    await page.getByRole('combobox', { name: 'Search' }).press('Enter');
});