// Generated by MyTester
// Run ID: run_f2a44af4-beec-4502-b406-987a25e670e8
// Test case ID: 6e253719-5a79-4988-a0e0-5b5fa088ec1a
// Generated at: 2026-08-13T13:44:55.980Z
import { test, expect } from '@playwright/test';
test('Vérification de l\'affichage du contrôle de sécurité Cloudflare à l\'accès', async ({ page }) => {
    await page.goto('https://www.wolterskluwer.com/en/solutions/enablon', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    await expect(page.locator('body')).toBeVisible();
    // Résultat attendu : Les éléments d'en-tête de sécurité et l'input masqué Turnstile 'cf-turnstile-response' sont correctement détectés dans le DOM.
});