// Generated by MyTester
// Run ID: run_f8d5fb19-d705-493f-a31f-1db3428b4ae2
// Test case ID: 79430ea5-6841-4fbe-9062-53e1e1c8dd3f
// Generated at: 2026-07-18T14:33:57.832Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://tek-up.de/');
    await page.getByRole('img', { name: 'Close' }).click();
    await page.locator('#gk-main-menu').getByRole('link', { name: ' Home' }).click();
    await page.getByRole('img', { name: 'Close' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('link', { name: 'TEK-UP University Job Fair JET' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('link', { name: 'Study & work (alternance)' }).click();
});