// Generated by MyTester
// Run ID: run_945cd1c4-6339-4d47-95fd-3a9e656a2221
// Test case ID: cc3c47bb-02ca-44a2-ba15-7dd14f045713
// Generated at: 2026-08-08T21:52:30.077Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.youtube.com/');
    await page.getByRole('combobox', { name: 'Search' }).click();
    await page.getByRole('combobox', { name: 'Search' }).fill('football');
    await page.getByRole('combobox', { name: 'Search' }).press('Enter');
});