// Generated by MyTester
// Run ID: run_f8e423e4-b04f-4364-a064-1b04ba0cfc20
// Test case ID: f6aa7308-ab29-49c7-ba8f-2876dbeb2ce1
// Generated at: 2026-07-13T02:42:53.631Z
import { test, expect } from '@playwright/test';
test('Vérifier le champ "Email *"', async ({ page }) => {
    await page.goto('https://workspace.lifeintelligente.com/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetField = page
        .getByLabel(/Email/i)
        .or(page.getByPlaceholder(/Email/i))
        .or(page.locator('input[name*="email" i], textarea[name*="email" i], input[id*="email" i], textarea[id*="email" i]'))
        .first();
    await expect(targetField).toBeVisible();
    await expect(targetField).toBeEnabled();
    await targetField.fill('test@example.com');
    await expect(targetField).toHaveValue('test@example.com');
    // Résultat attendu : Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
});