// Generated by MyTester
// Run ID: run_6d056416-6be6-4d63-bfba-21b8967bb7d8
// Test case ID: 3ffda29c-77fc-49c5-b44e-9ce0f79a3fe7
// Generated at: 2026-07-18T14:00:13.675Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('button', { name: 'Sign in to your account' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('button', { name: 'Google' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('textbox', { name: 'Email or phone' }).click();
    await page1.getByRole('textbox', { name: 'Email or phone' }).fill('hhhhh');
    await page1.getByRole('textbox', { name: 'Email or phone' }).press('Enter');
});