// Generated by MyTester
// Run ID: run_e06b132d-e94c-4083-bc49-0849aaa3343e
// Test case ID: 3ffda29c-77fc-49c5-b44e-9ce0f79a3fe7
// Generated at: 2026-07-17T07:32:57.222Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('button', { name: 'Sign in to your account' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('button', { name: 'Google' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('textbox', { name: 'Email or phone' }).click();
    await page1.getByRole('textbox', { name: 'Email or phone' }).fill('hhhhh');
    await page1.getByRole('textbox', { name: 'Email or phone' }).press('Enter');
});