// Generated by MyTester
// Run ID: run_933fade4-2947-4d52-9d42-10283e4be767
// Test case ID: 05331ea4-2ef5-41de-ba41-fa2aa8691d2d
// Generated at: 2026-08-14T00:53:02.275Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.sofrecom.com/');
    await page.getByRole('button', { name: 'Allow all' }).click();
    await page.getByRole('button', { name: 'Nos Marchés' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).fill('ismail');
    await page.getByRole('textbox', { name: 'Recherche' }).press('Enter');
});