// Generated by MyTester
// Run ID: run_cb3efc5a-fe38-462d-8669-c477d7861a6d
// Test case ID: 48dae334-ae91-4bd1-b3fe-74700cb8a044
// Generated at: 2026-07-18T14:01:42.758Z
import { test, expect } from '@playwright/test';
test('Vérifier les erreurs console', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    // Step 1: Ouvrir l'application : https://www.w3schools.com/
    // TODO: implement this step
    // Expected: La page doit se charger correctement sans erreur bloquante.
    // Step 2: Ouvrir la console navigateur et surveiller les erreurs JavaScript.
    const consoleErrors = [];
    page.on('console', (msg) => {
        if (msg.type() === 'error')
            consoleErrors.push(msg.text());
    });
    expect(consoleErrors).toHaveLength(0);
    // Expected: Aucune erreur critique ne doit apparaître pendant le chargement.
    // Step 3: Vérifier le résultat final du scénario.
    // TODO: implement this step
    // Expected: Aucune erreur JavaScript critique ne doit apparaître dans la console.
    // Global expected result
    await expect(page.locator('body')).toContainText('Aucune erreur JavaScript critique ne doit apparaître dans la console.');
});