// Generated by MyTester
// Run ID: run_9a5add98-9e63-48a9-8751-2bf6f9ac7186
// Test case ID: 223386ae-81d9-44c6-90cb-197eeca956c4
// Generated at: 2026-08-19T20:21:51.431Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.tunisianet.com.tn/panier?action=show');
    await page.getByText('Téléphonie & Tablette', { exact: true }).click();
    await page.getByRole('link', { name: 'Tablette Graphique' }).click();
    await page.getByRole('article').filter({ hasText: 'TABLETTE D\'ECRITURE ET DE DESSIN 12" LCD -VERT [TAB-LCD-VR] Tablette D\'ecriture' }).getByRole('button').click();
});