// Generated by MyTester
// Run ID: run_9bb32b05-c0f0-4416-b3e1-a280db10675b
// Test case ID: b8364d54-9088-48ba-8dff-d7d2ff858f75
// Generated at: 2026-07-13T02:37:45.058Z
import { test, expect } from '@playwright/test';
test('Vérifier le champ "Prénom *"', async ({ page }) => {
    await page.goto('https://workspace.lifeintelligente.com/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetField = page
        .getByLabel(/Prénom/i)
        .or(page.getByPlaceholder(/Prénom/i))
        .or(page.locator('input[name*="prenom" i], textarea[name*="prenom" i], input[id*="prenom" i], textarea[id*="prenom" i]'))
        .first();
    await expect(targetField).toBeVisible();
    await expect(targetField).toBeEnabled();
    await targetField.fill('Mohsen');
    await expect(targetField).toHaveValue('Mohsen');
    // Résultat attendu : Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
});