// Generated by MyTester
// Run ID: run_492ca5bf-8618-4427-9e05-a3470f5eb92e
// Test case ID: 9a45f825-5fce-40cf-b6a3-c01dc6b254b4
// Generated at: 2026-07-13T00:23:30.921Z
import { test, expect } from '@playwright/test';

test('Vérifier le champ "Nom *"', async ({ page }) => {
  // Step 1: Préparer la surveillance de la console navigateur avant le chargement.
  // Expected: Toutes les erreurs JavaScript de type "error" doivent être capturées.
  const consoleErrors: string[] = [];

  page.on('console', (msg) => {
    if (msg.type() === 'error') {
      consoleErrors.push(msg.text());
    }
  });

  // Step 2: Ouvrir l'application : https://workspace.lifeintelligente.com/
  // Expected: La page doit se charger correctement sans erreur bloquante.
  await page.goto('https://workspace.lifeintelligente.com/');

  // Vérification de la structure globale de la page.
  // Expected: Les éléments principaux de l'application doivent être visibles.
  await expect(page.locator('body')).toBeVisible();
  await expect(page.locator('header, nav').first()).toBeVisible();
  await expect(page.locator('footer')).toBeVisible();
  await expect(page.locator('img[alt*="logo" i]').first()).toBeVisible();

  // Step 3: Renseigner les champs du formulaire avec des données valides.
  // Expected: Les champs doivent accepter les données saisies.
  await expect(page.locator('form, input, textarea, select').first()).toBeVisible();

  // Step 4: Soumettre le formulaire.
  // Expected: Le système doit traiter la demande et afficher un retour clair.
  await expect(page.locator('form, input, textarea, select').first()).toBeVisible();

  // Step 5: Vérifier le résultat final du scénario.
  // Expected: Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
  await expect(page.locator('#contact')).toBeVisible();

  // Vérification de base : la page doit rester accessible.
  await expect(page.locator('body')).toBeVisible();

  // Vérification console
  // Expected: Aucune erreur JavaScript critique ne doit apparaître dans la console.
  expect(consoleErrors).toHaveLength(0);

  // Global expected result
  // Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
});