// Generated by MyTester
// Run ID: run_50ea62fa-70d5-427f-b579-049059d829f9
// Test case ID: 89347edb-bcfa-48d5-894a-72c8c3fdd87d
// Generated at: 2026-07-17T07:33:15.370Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('link', { name: 'Home link' }).click();
    await page.getByRole('button', { name: 'Sign in to your account' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('button', { name: 'Facebook' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('textbox', { name: 'Email or mobile number' }).click();
    await page1.getByRole('textbox', { name: 'Email or mobile number' }).fill('ffff');
    await page1.getByRole('textbox', { name: 'Password' }).click();
    await page1.getByRole('textbox', { name: 'Password' }).fill('ppppp');
    await page1.getByRole('button', { name: 'Log In' }).click();
});