// Generated by MyTester
// Run ID: run_c4d06f4b-3644-4b0f-90d2-7c922ca46f82
// Test case ID: 05331ea4-2ef5-41de-ba41-fa2aa8691d2d
// Generated at: 2026-08-14T00:53:57.081Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.sofreco.com/');
    await page.getByRole('button', { name: 'Allow all' }).click();
    await page.getByRole('button', { name: 'Nos Marchés' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).fill('ismail');
    await page.getByRole('textbox', { name: 'Recherche' }).press('Enter');
});