// Generated by MyTester
// Run ID: run_c6514f74-719b-4c64-920b-37ab591975a6
// Test case ID: e47cb116-3742-4778-b49c-b82856120e09
// Generated at: 2026-07-18T16:12:17.439Z
import { test, expect } from '@playwright/test';
test('Vérifier le chargement de la page "W3Schools Online Web Tutorials"', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    // Step 1: Ouvrir l'application : https://www.w3schools.com/
    // TODO: implement this step
    // Expected: La page doit se charger correctement sans erreur bloquante.
    // Step 2: Ouvrir la console navigateur et surveiller les erreurs JavaScript.
    const consoleErrors = [];
    page.on('console', (msg) => {
        if (msg.type() === 'error')
            consoleErrors.push(msg.text());
    });
    expect(consoleErrors).toHaveLength(0);
    // Expected: Aucune erreur critique ne doit apparaître pendant le chargement.
    // Step 3: Vérifier le résultat final du scénario.
    // TODO: implement this step
    // Expected: La page doit afficher son contenu principal et rester accessible.
    // Global expected result
    await expect(page.locator('body')).toContainText('La page doit afficher son contenu principal et rester accessible.');
});