// Generated by MyTester
// Run ID: run_e0881e7b-ca49-4c3f-8311-c77cfe8230dc
// Test case ID: f94c1102-d078-4fe6-9fa4-b36435e13e03
// Generated at: 2026-08-14T01:00:06.238Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.tunisianet.com.tn/');
    await page.getByText('Informatique', { exact: true }).click();
    await page.getByRole('link', { name: 'Ecran', exact: true }).click();
    await page.getByRole('link', { name: 'Écran Enter ECR-MO-A012 19" HD / VGA / HDMI / 75 Hz', exact: true }).click();
    await page.getByRole('button').nth(1).click();
    await page.getByRole('button', { name: 'Ajouter au panier' }).click();
    await page.getByRole('button', { name: 'Continuer' }).click();
});