// Generated by MyTester
// Run ID: run_8d30383c-c561-4666-9b52-6d0bac9545df
// Test case ID: 0648999a-0099-4541-9d68-f2f7e7df56af
// Generated at: 2026-07-17T00:10:52.674Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.youtube.com/');
    await page.getByRole('link', { name: 'Home', description: 'Home', exact: true }).click();
    await page.getByRole('combobox', { name: 'Search' }).click();
    await page.getByRole('combobox', { name: 'Search' }).fill('crestiano');
    await page.goto('https://www.youtube.com/shorts/hCzwv9RPLkE');
});