// Generated by MyTester
// Run ID: run_6dcde8f6-6a64-4df6-b694-b038422ab387
// Test case ID: b8364d54-9088-48ba-8dff-d7d2ff858f75
// Generated at: 2026-07-13T03:07:30.592Z
import { test, expect } from '@playwright/test';
test('Vérifier le champ "Prénom *"', async ({ page }) => {
    await page.goto('https://workspace.lifeintelligente.com/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetField = page
        .getByLabel(/Prénom/i)
        .or(page.getByPlaceholder(/Prénom/i))
        .or(page.locator('input[name*="prenom" i], textarea[name*="prenom" i], input[id*="prenom" i], textarea[id*="prenom" i]'))
        .first();
    await expect(targetField).toBeVisible();
    await expect(targetField).toBeEnabled();
    await targetField.fill('Mohsen');
    await expect(targetField).toHaveValue('Mohsen');
    // Résultat attendu : Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
});