// Generated by MyTester
// Run ID: run_ff36f82e-826e-4265-9147-820508d04edf
// Test case ID: df72b353-0ca3-4054-9dd5-18bf3a8521dc
// Generated at: 2026-08-08T22:27:36.446Z
import { test, expect } from '@playwright/test';
test('Vérifier la navigation vers "Exercises"', async ({ page }) => {
    await page.goto('https://www.w3schools.com/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetLink = page
        .getByRole('link', { name: /Exercises/i })
        .or(page.getByText(/Exercises/i))
        .first();
    await expect(targetLink).toBeVisible();
    await targetLink.click();
    await page.waitForLoadState('domcontentloaded');
    await expect(page.locator('body')).toBeVisible();
    // Résultat attendu : L’utilisateur doit être redirigé vers la bonne page.
});