// Generated by MyTester
// Run ID: run_d9e09ad8-854e-4190-b2dd-81b975233761
// Test case ID: 84bf2c3d-e813-47e1-a2bd-8810575a0286
// Generated at: 2026-07-13T02:42:32.934Z
import { test, expect } from '@playwright/test';
test('Vérifier le champ "Sujet"', async ({ page }) => {
    await page.goto('https://workspace.lifeintelligente.com/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetField = page
        .getByLabel(/Sujet/i)
        .or(page.getByPlaceholder(/Sujet/i))
        .or(page.locator('input[name*="sujet" i], textarea[name*="sujet" i], input[id*="sujet" i], textarea[id*="sujet" i]'))
        .first();
    await expect(targetField).toBeVisible();
    await expect(targetField).toBeEnabled();
    await targetField.fill('Demande de test');
    await expect(targetField).toHaveValue('Demande de test');
    // Résultat attendu : Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
});