// Generated by MyTester
// Run ID: run_a61ce4d5-d31b-428d-b2a3-e0266cb219e2
// Test case ID: 79430ea5-6841-4fbe-9062-53e1e1c8dd3f
// Generated at: 2026-08-02T08:18:45.790Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://tek-up.de/');
    await page.getByRole('img', { name: 'Close' }).click();
    await page.locator('#gk-main-menu').getByRole('link', { name: ' Home' }).click();
    await page.getByRole('img', { name: 'Close' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('link', { name: 'TEK-UP University Job Fair JET' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('link', { name: 'Study & work (alternance)' }).click();
});