// Generated by MyTester
// Run ID: run_bb0ec589-00fa-4416-8e4d-ff9450336b03
// Test case ID: 95b45de3-6ce7-41f5-b67c-bb3f3836c3ac
// Generated at: 2026-08-06T07:54:13.332Z
import { test, expect } from '@playwright/test';
test('Vérifier la navigation vers "Pour vous"', async ({ page }) => {
    await page.goto('https://www.eurosport.fr/football/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetLink = page
        .getByRole('link', { name: /Pour vous/i })
        .or(page.getByText(/Pour vous/i))
        .first();
    await expect(targetLink).toBeVisible();
    await targetLink.click();
    await page.waitForLoadState('domcontentloaded');
    await expect(page.locator('body')).toBeVisible();
    // Résultat attendu : L’utilisateur doit être redirigé vers la bonne page.
});