// Generated by MyTester
// Run ID: run_49d13779-a681-4a77-8032-01a224ac5de9
// Test case ID: bf5ca731-9292-4fda-af25-b799a0c2b12b
// Generated at: 2026-07-13T01:01:32.476Z
import { test, expect } from '@playwright/test';
test('Vérifier le champ "Prénom *"', async ({ page }) => {
    // Step 1: Préparer la surveillance de la console navigateur avant le chargement.
    // Expected: Toutes les erreurs JavaScript de type "error" doivent être capturées.
    const consoleErrors = [];
    page.on('console', (msg) => {
        if (msg.type() === 'error') {
            consoleErrors.push(msg.text());
        }
    });
    // Step 2: Ouvrir l'application : https://workspace.lifeintelligente.com/
    // Expected: La page doit se charger correctement sans erreur bloquante.
    await page.goto('https://workspace.lifeintelligente.com/');
    // Vérification de la structure globale de la page.
    // Expected: Les éléments principaux de l'application doivent être visibles.
    await expect(page.locator('body')).toBeVisible();
    await expect(page.locator('header, nav').first()).toBeVisible();
    await expect(page.locator('footer')).toBeVisible();
    await expect(page.locator('img[alt*="logo" i]').first()).toBeVisible();
    // Step 3: Renseigner les champs du formulaire avec des données valides.
    // Expected: Les champs doivent accepter les données saisies.
    await expect(page.locator('form, input, textarea, select').first()).toBeVisible();
    // Step 4: Soumettre le formulaire.
    // Expected: Le système doit traiter la demande et afficher un retour clair.
    await expect(page.locator('form, input, textarea, select').first()).toBeVisible();
    // Step 5: Vérifier le résultat final du scénario.
    // Expected: Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
    await expect(page.locator('#contact')).toBeVisible();
    // Vérification de base : la page doit rester accessible.
    await expect(page.locator('body')).toBeVisible();
    // Vérification console
    // Expected: Aucune erreur JavaScript critique ne doit apparaître dans la console.
    expect(consoleErrors).toHaveLength(0);
    // Global expected result
    // Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
});