// Generated by MyTester
// Run ID: run_3ff82968-edcf-4cb1-ab69-18ea33dbfa2c
// Test case ID: abd67bd4-1e98-4e55-a817-fe5b70ad6257
// Generated at: 2026-07-13T02:40:50.783Z
import { test, expect } from '@playwright/test';
test('Vérifier l’action du bouton "Réserver"', async ({ page }) => {
    await page.goto('https://workspace.lifeintelligente.com/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetButton = page
        .getByRole('button', { name: /Réserver/i })
        .or(page.getByText(/Réserver/i))
        .first();
    await expect(targetButton).toBeVisible();
    await expect(targetButton).toBeEnabled();
    await targetButton.click();
    await expect(page.locator('body')).toBeVisible();
    // Résultat attendu : Le bouton doit déclencher l’action prévue sans erreur.
});