// Generated by MyTester
// Run ID: run_d9ee7bfb-b885-433a-89df-21a5cded7949
// Test case ID: e4c23b9a-9c51-439c-9b65-ff419f15107b
// Generated at: 2026-07-13T00:11:23.471Z
import { test, expect } from '@playwright/test';

test('Vérifier le chargement de la page "Life Intelligente - Espace de Coworking Moderne"', async ({ page }) => {
  // Step 1: Préparer la surveillance de la console navigateur avant le chargement.
  // Expected: Toutes les erreurs JavaScript de type "error" doivent être capturées.
  const consoleErrors: string[] = [];

  page.on('console', (msg) => {
    if (msg.type() === 'error') {
      consoleErrors.push(msg.text());
    }
  });

  // Step 2: Ouvrir l'application : https://workspooce.lifeintelligente.com/
  // Expected: La page doit se charger correctement sans erreur bloquante.
  await page.goto('https://workspooooce.lifeintelligente.com/');

  // Vérification de la structure globale de la page.
  // Expected: Les éléments principaux de l'application doivent être visibles.
  await expect(page.locator('body')).toBeVisible();
  await expect(page.locator('header, nav').first()).toBeVisible();
  await expect(page.locator('footer')).toBeVisible();
  await expect(page.locator('img[alt*="logo" i]').first()).toBeVisible();

  // Step 3: Vérifier le résultat final du scénario.
  // Expected: La page doit afficher son contenu principal et rester accessible.
  await expect(page.locator('#home')).toBeVisible();

  // Vérification de base : la page doit rester accessible.
  await expect(page.locator('body')).toBeVisible();

  // Vérification console
  // Expected: Aucune erreur JavaScript critique ne doit apparaître dans la console.
  expect(consoleErrors).toHaveLength(0);

  // Global expected result
  // La page doit afficher son contenu principal et rester accessible.
});