// Generated by MyTester
// Run ID: run_f04d887b-608a-470b-b327-4c1228aba12d
// Test case ID: 104b643f-c40f-46b2-b7f1-16539d9d4216
// Generated at: 2026-07-22T09:39:56.121Z
import { test, expect } from '@playwright/test';
const TRANSLATE_URL = 'https://translate.google.com/?sl=en&tl=fr&op=translate';
const TEST_TEXT = 'Hello, this is a test.';
async function getSourceTextField(page) {
    const accessibleTextbox = page
        .getByRole('textbox')
        .filter({ visible: true })
        .first();
    const fallbackTextarea = page
        .locator([
        'textarea[aria-label]',
        'textarea[placeholder]',
        'textarea',
        '[contenteditable="true"][role="textbox"]',
    ].join(', '))
        .filter({ visible: true })
        .first();
    if (await accessibleTextbox.count()) {
        return accessibleTextbox;
    }
    return fallbackTextarea;
}
test.describe('Google Traduction', () => {
    test('le champ source accepte un texte valide', async ({ page }) => {
        await test.step('Ouvrir Google Traduction', async () => {
            await page.goto(TRANSLATE_URL, {
                waitUntil: 'domcontentloaded',
                timeout: 30_000,
            });
            await expect(page).toHaveURL(/translate\.google\.com/);
            await expect(page.locator('body')).toBeVisible();
        });
        const sourceField = await getSourceTextField(page);
        await test.step('Vérifier que le champ source est utilisable', async () => {
            await expect(sourceField, 'Le champ de saisie source doit être visible').toBeVisible({ timeout: 15_000 });
            await expect(sourceField, 'Le champ de saisie source doit être activé').toBeEnabled();
        });
        await test.step('Saisir et vérifier le texte', async () => {
            await sourceField.fill(TEST_TEXT);
            await expect(sourceField).toHaveValue(TEST_TEXT);
        });
    });
});