// Generated by MyTester
// Run ID: run_74a9d9fb-3bd9-4c78-a046-58d1772465ee
// Test case ID: 05331ea4-2ef5-41de-ba41-fa2aa8691d2d
// Generated at: 2026-08-14T00:52:19.712Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.sofrecom.com/');
    await page.getByRole('button', { name: 'Allow all' }).click();
    await page.getByRole('button', { name: 'Nos Marchés' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).fill('ismail');
    await page.getByRole('textbox', { name: 'Recherche' }).press('Enter');
});