// Generated by MyTester
// Run ID: run_66c25368-be59-4e03-a918-1b740045b658
// Test case ID: 8a78b03c-331d-4c50-a5f2-c46a288d3749
// Generated at: 2026-07-18T15:55:53.813Z
import { test, expect } from '@playwright/test';
test('Vérifier le chargement de la page "Just a moment..."', async ({ page }) => {
    await page.goto('https://www.fbi.gov/investigate', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    await expect(page).toHaveTitle(/.+/);
    // Résultat attendu : La page doit afficher son contenu principal et rester accessible.
});