// Generated by MyTester
// Run ID: run_4469c3b0-d687-4134-ab61-44a4027cf649
// Test case ID: 43977754-e12c-40da-9adb-4ec53fb3dfd6
// Generated at: 2026-08-08T16:34:29.584Z
import { test, expect } from '@playwright/test';
test('Exécution d\'une recherche via le champ de recherche', async ({ page }) => {
    await page.goto('https://www.youtube.com', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetField = page
        .getByLabel(/Exécution d'une recherche via le   de recherche/i)
        .or(page.getByPlaceholder(/Exécution d'une recherche via le   de recherche/i))
        .or(page.locator('input[name*="executiondunerecherchevialederecherche" i], textarea[name*="executiondunerecherchevialederecherche" i], input[id*="executiondunerecherchevialederecherche" i], textarea[id*="executiondunerecherchevialederecherche" i]'))
        .first();
    await expect(targetField).toBeVisible();
    await expect(targetField).toBeEnabled();
    await targetField.fill('Valeur de test');
    await expect(targetField).toHaveValue('Valeur de test');
    // Résultat attendu : Le formulaire soumet la requête de recherche vers 'https://www.youtube.com/results'.
});