// Generated by MyTester
// Run ID: run_1d7cf97a-2a9e-4311-aa3b-36aa948ffc37
// Test case ID: 4f1f23f2-39ad-4c57-9e6e-2441db5c1382
// Generated at: 2026-08-19T21:10:22.001Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.sofrecom.com/');
    await page.getByRole('button', { name: 'Allow all' }).click();
    await page.getByRole('button', { name: 'Nos Marchés' }).click();
    await page.getByRole('link', { name: 'Contactez-nous' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).fill('fatma');
});