// Generated by MyTester
// Run ID: run_8ce5bed0-1530-4cd5-bdc4-a4e951910f57
// Test case ID: 95b45de3-6ce7-41f5-b67c-bb3f3836c3ac
// Generated at: 2026-08-19T20:23:51.886Z
import { test, expect } from '@playwright/test';
test('Vérifier la navigation vers "Pour vous"', async ({ page }) => {
    await page.goto('https://www.eurosport.fr/football/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetLink = page
        .getByRole('link', { name: /Pour vous/i })
        .or(page.getByText(/Pour vous/i))
        .first();
    await expect(targetLink).toBeVisible();
    await targetLink.click();
    await page.waitForLoadState('domcontentloaded');
    await expect(page.locator('body')).toBeVisible();
    // Résultat attendu : L’utilisateur doit être redirigé vers la bonne page.
});