// Generated by MyTester
// Run ID: run_843cc54d-6fc0-427e-bf56-34e60a2492af
// Test case ID: 104b643f-c40f-46b2-b7f1-16539d9d4216
// Generated at: 2026-07-22T09:32:16.248Z
import { test, expect } from '@playwright/test';
test('Vérifier le champ "Light"', async ({ page }) => {
    await page.goto('https://translate.google.com/?sl=en&tl=fr&op=translate', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetField = page
        .getByLabel(/Light/i)
        .or(page.getByPlaceholder(/Light/i))
        .or(page.locator('input[name*="light" i], textarea[name*="light" i], input[id*="light" i], textarea[id*="light" i]'))
        .first();
    await expect(targetField).toBeVisible();
    await expect(targetField).toBeEnabled();
    await targetField.fill('Valeur de test');
    await expect(targetField).toHaveValue('Valeur de test');
    // Résultat attendu : Le champ doit accepter les données valides et afficher une validation claire si nécessaire.
});