// Generated by MyTester
// Run ID: run_cabd308f-adad-4530-a100-71e99687e653
// Test case ID: 3ffda29c-77fc-49c5-b44e-9ce0f79a3fe7
// Generated at: 2026-07-18T16:14:39.912Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('button', { name: 'Sign in to your account' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('button', { name: 'Google' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('textbox', { name: 'Email or phone' }).click();
    await page1.getByRole('textbox', { name: 'Email or phone' }).fill('hhhhh');
    await page1.getByRole('textbox', { name: 'Email or phone' }).press('Enter');
});