// Generated by MyTester
// Run ID: run_b18bbc92-4303-42ce-ad2c-f522b68aed36
// Test case ID: 04d2e45f-be6c-4a17-9281-618c89eb9be6
// Generated at: 2026-08-13T13:29:13.661Z
import { test, expect } from '@playwright/test';
test('Contrôle des liens d\'information Cloudflare sur la page de défi de sécurité', async ({ page }) => {
    await page.goto('https://www.wolterskluwer.com/en/solutions/enablon', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetLink = page
        .getByRole('link', { name: /Contrôle des  s d'information Cloudflare sur la page de défi de sécurité/i })
        .or(page.getByText(/Contrôle des  s d'information Cloudflare sur la page de défi de sécurité/i))
        .first();
    await expect(targetLink).toBeVisible();
    await targetLink.click();
    await page.waitForLoadState('domcontentloaded');
    await expect(page.locator('body')).toBeVisible();
    // Résultat attendu : Les liens vers le site Cloudflare et sa politique de confidentialité sont correctement référencés.
});