// Generated by MyTester
// Run ID: run_2e1b5294-4abf-4b88-a6d5-a8ec2531bd48
// Test case ID: 79430ea5-6841-4fbe-9062-53e1e1c8dd3f
// Generated at: 2026-07-18T14:29:15.686Z
import { test, expect } from '@playwright/test';
test('Vérifier l’action du bouton "Open TEK-UP University"', async ({ page }) => {
    await page.goto('https://tek-up.de/', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    const targetButton = page
        .getByRole('button', { name: /Open TEK-UP University/i })
        .or(page.getByText(/Open TEK-UP University/i))
        .first();
    await expect(targetButton).toBeVisible();
    await expect(targetButton).toBeEnabled();
    await targetButton.click();
    await expect(page.locator('body')).toBeVisible();
    // Résultat attendu : Le bouton doit déclencher l’action prévue sans erreur.
});