// Generated by MyTester
// Run ID: run_fa06d416-2ab3-410c-917c-7df4342a0d0a
// Test case ID: 6e253719-5a79-4988-a0e0-5b5fa088ec1a
// Generated at: 2026-08-13T13:30:29.779Z
import { test, expect } from '@playwright/test';
test('Vérification de l\'affichage du contrôle de sécurité Cloudflare à l\'accès', async ({ page }) => {
    await page.goto('https://www.wolterskluwer.com/en/solutions/enablon', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    await expect(page.locator('body')).toBeVisible();
    // Résultat attendu : Les éléments d'en-tête de sécurité et l'input masqué Turnstile 'cf-turnstile-response' sont correctement détectés dans le DOM.
});