// Generated by MyTester
// Run ID: run_6230e1d0-02b6-4940-98f8-4ab3bf66be55
// Test case ID: f106e10c-1f35-4d80-84d7-af6acdedcc88
// Generated at: 2026-07-13T00:42:06.188Z
import { test, expect } from '@playwright/test';

test(
  'Vérifier le chargement de la page "Life Intelligente - Espace de Coworking Moderne"',
  async ({ page }) => {
    // Step 1 : surveiller les erreurs console.
    const consoleErrors = [];

    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        consoleErrors.push(msg.text());
      }
    });

    // Step 2 : ouvrir l’application.
    await page.goto(
      'https://workspace.lifeintelligente.com/',
      {
        waitUntil: 'domcontentloaded',
      },
    );

    await expect(page.locator('body')).toBeVisible();
    await expect(
      page.locator('header, nav').first(),
    ).toBeVisible();
    await expect(
      page.locator('footer'),
    ).toBeVisible();
    await expect(
      page.locator('img[alt*="logo" i]').first(),
    ).toBeVisible();

    // Step 3 : vérifier le contenu principal.
    await expect(
      page.locator('#home'),
    ).toBeVisible();

    await expect(
      page.locator('body'),
    ).toBeVisible();

    // Vérification console.
    expect(consoleErrors).toHaveLength(0);
  },
);