// Generated by MyTester
// Run ID: run_b19e111c-06ed-48f1-94fd-d9d0cb84226f
// Test case ID: 8a78b03c-331d-4c50-a5f2-c46a288d3749
// Generated at: 2026-07-18T15:57:06.596Z
import { test, expect } from '@playwright/test';
test('Vérifier le chargement de la page "Just a moment..."', async ({ page }) => {
    await page.goto('https://www.fbi.gov/investigate', {
        waitUntil: 'domcontentloaded',
    });
    await expect(page.locator('body')).toBeVisible();
    await expect(page).toHaveTitle(/.+/);
    // Résultat attendu : La page doit afficher son contenu principal et rester accessible.
});