// Generated by MyTester
// Run ID: run_f9255240-cffc-4820-ac23-f6ee3d432df6
// Test case ID: 3d14a506-896b-4fb3-8063-41f3e592ca06
// Generated at: 2026-07-16T23:31:32.431Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.speedtest.net/');
    await page.getByRole('link', { name: 'Speedtest', exact: true }).click();
    await page.goto('https://www.speedtest.net/');
    await page.getByRole('button', { name: 'start speed test - connection' }).click();
    await page.goto('https://www.speedtest.net/result/19421044671');
    await page.getByRole('link', { name: 'Speedtest', exact: true }).click();
});