// Generated by MyTester
// Run ID: run_cef3ba15-3bad-44dd-8bf0-695a6ecde3f5
// Test case ID: cc3c47bb-02ca-44a2-ba15-7dd14f045713
// Generated at: 2026-08-08T21:57:36.851Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.youte.com/');
    await page.getByRole('combobox', { name: 'Search' }).click();
    await page.getByRole('combobox', { name: 'Search' }).fill('football');
    await page.getByRole('combobox', { name: 'Search' }).press('Enter');
});