// Generated by MyTester
// Run ID: run_3c1a3299-018d-4195-8925-a8a4e529356a
// Test case ID: f94c1102-d078-4fe6-9fa4-b36435e13e03
// Generated at: 2026-08-07T09:34:45.685Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.tunisianet.com.tn/');
    await page.getByText('Informatique', { exact: true }).click();
    await page.getByRole('link', { name: 'Ecran', exact: true }).click();
    await page.getByRole('link', { name: 'Écran Enter ECR-MO-A012 19" HD / VGA / HDMI / 75 Hz', exact: true }).click();
    await page.getByRole('button').nth(1).click();
    await page.getByRole('button', { name: 'Ajouter au panier' }).click();
    await page.getByRole('button', { name: 'Continuer' }).click();
});