// Generated by MyTester
// Run ID: run_5a38ad8c-3751-43c6-ac7e-7ec4c47fbae6
// Test case ID: f808e4d3-a6fe-4e9b-abc6-de6fc6750973
// Generated at: 2026-07-17T00:41:17.363Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('link', { name: 'Home link' }).click();
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('link', { name: 'Home link' }).click();
    await page.getByRole('button', { name: 'Sign in to your account' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('button', { name: 'Google' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('textbox', { name: 'Email or phone' }).click();
    await page1.getByRole('textbox', { name: 'Email or phone' }).fill('hhh');
    await page1.getByRole('button', { name: 'Next' }).click();
});