// Generated by MyTester
// Run ID: run_e0ab7ca9-d916-4bea-8446-29400239509d
// Test case ID: 063474ad-ac3b-4aa4-9ef5-35759463ea12
// Generated at: 2026-08-06T07:33:06.527Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('link', { name: 'SQL', exact: true }).click();
    await page.locator('.w3-code').click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('link', { name: 'Try it Yourself »' }).click();
    const page1 = await page1Promise;
    await page1.locator('pre').nth(1).click();
    await page1.getByText('Customers;', { exact: true }).click();
    await page1.locator('pre').nth(1).click();
    await page1.getByRole('textbox').fill('println()');
});