// Generated by MyTester
// Run ID: run_2049e0d3-2b5c-4fd2-a1e4-267fd9890386
// Test case ID: 5c70783b-ab69-4241-8c88-e2d9496dc9dc
// Generated at: 2026-07-17T00:10:25.818Z
import { test, expect } from '@playwright/test';
test('Vérifier le chargement de la page "YouTube"', async ({ page }) => {
    // Step 1: Préparer la surveillance de la console navigateur avant le chargement.
    // Expected: Toutes les erreurs JavaScript de type "error" doivent être capturées.
    const consoleErrors = [];
    page.on('console', (msg) => {
        if (msg.type() === 'error') {
            consoleErrors.push(msg.text());
        }
    });
    // Step 2: Ouvrir l'application : https://www.youtube.com/
    // Expected: La page doit se charger correctement sans erreur bloquante.
    await page.goto('https://www.youtube.com/');
    // Vérification de la structure globale de la page.
    // Expected: Les éléments principaux de l'application doivent être visibles.
    await expect(page.locator('body')).toBeVisible();
    await expect(page.locator('#logo').first()).toBeVisible();
    // Step 3: Vérifier le résultat final du scénario.
    // Expected: La page doit afficher son contenu principal et rester accessible.
    await expect(page.getByText(/YouTube/i).first()).toBeVisible();
    // Vérification de base : la page doit rester accessible.
    await expect(page.locator('body')).toBeVisible();
    // Vérification console
    // Expected: Aucune erreur JavaScript critique ne doit apparaître dans la console.
    expect(consoleErrors).toHaveLength(0);
    // Global expected result
    // La page doit afficher son contenu principal et rester accessible.
});