// Generated by MyTester
// Run ID: run_d8da5f6b-ffe4-447a-aa84-8425ad9e0276
// Test case ID: aedb4bf2-8348-42be-8781-d712bbb621c9
// Generated at: 2026-08-14T01:00:41.642Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.w3schools.com/');
    await page.getByRole('link', { name: 'Home link' }).click();
    await page.getByRole('button', { name: 'Sign in to your account' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('button', { name: 'Google' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('textbox', { name: 'Email or phone' }).click();
    await page1.getByRole('textbox', { name: 'Email or phone' }).fill('aaaaa');
    await page1.getByRole('button', { name: 'Next' }).click();
});