// Generated by MyTester
// Run ID: run_c0a1a1ca-1993-4548-b2ba-28a9637a256e
// Test case ID: 4f1f23f2-39ad-4c57-9e6e-2441db5c1382
// Generated at: 2026-08-19T21:08:14.127Z
import { test } from '@playwright/test';
test('test', async ({ page }) => {
    await page.goto('https://www.sofrecom.com/');
    await page.getByRole('button', { name: 'Allow all' }).click();
    await page.getByRole('button', { name: 'Nos Marchés' }).click();
    await page.getByRole('link', { name: 'Contactez-nous' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).click();
    await page.getByRole('textbox', { name: 'Recherche' }).fill('fatma');
});